from typing import Protocol


class LLMClient(Protocol):
    async def complete(self, prompt: str) -> str:
        """Return text generated by the configured LLM provider."""


class OpenAILLMClient:
    async def complete(self, prompt: str) -> str:
        raise NotImplementedError("OpenAI integration starts after the Stage 1.2 skeleton.")
